kind: Service
apiVersion: v1
metadata:
  name: csi-attacher-unity
  labels:
    app: csi-attacher-unity
spec:
  selector:
    app: csi-attacher-unity
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-attacher-unity
spec:
  serviceName: "csi-attacher-unity"
  replicas: 1
  selector:
    matchLabels:
      app: csi-attacher-unity
  template:
    metadata:
      labels:
        app: csi-attacher-unity
    spec:
      serviceAccount: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v0.4.0
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-unity
            type: DirectoryOrCreate
          name: socket-dir
