kind: Service
apiVersion: v1
metadata:
  name: csi-snapshotter-unity 
  labels:
    app: csi-snapshotter-unity 
spec:
  selector:
    app: csi-snapshotter-unity 
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-snapshotter-unity
spec:
  serviceName: "csi-snapshotter-unity"
  replicas: 1
  selector:
    matchLabels:
      app: csi-snapshotter-unity
  template:
    metadata:
      labels:
        app: csi-snapshotter-unity
    spec:
      serviceAccount: csi-snapshotter
      containers:
        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v0.4.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--connection-timeout=15s"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-unity
            type: DirectoryOrCreate
          name: socket-dir
